const dogList = [
    {
        id: 1,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 2,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 3,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 4,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 5,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 6,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 7,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 8,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 9,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 10,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 11,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 12,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 13,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 14,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 15,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 16,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 17,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 18,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    }
]

export default dogList