const dogList = [
    {
        id: 1,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 2,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 3,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 4,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 5,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    },
    {
        id: 6,
        breed:"Pitbull",
        weeks:"5",
        months:"2",
        isVaccinated:true,
        isMixedBreed:true,
        motherBreed:"Poodle",
        fatherBreed:"Pitbull",
        photos:[],
        ownerName:"Satyam Mahajan",
        colors:["white", "black"],
        waLink: "",
    }
]

export default dogList